server {
    listen 80;
    listen [::]:80;
    server_name __AUTH_DOMAIN__ www.__AUTH_DOMAIN__;

    access_log off;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
