use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_lua.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let libs_dir = Path::new(&manifest_dir).join("../../libraries/open_source");

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(dir) = fs::read_dir(&libs_dir) {
        for entry in dir.flatten() {
            let path = entry.path();
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
            if ext == "lua" || ext == "bin" {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    let rel = path
                        .strip_prefix(&manifest_dir)
                        .ok()
                        .and_then(|p| p.to_str())
                        .map(|s| s.replace('\\', "/"))
                        .unwrap_or_default();
                    entries.push((stem.to_string(), rel));
                }
            }
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs\n\n");
    code.push_str("#[inline]\n");
    code.push_str("pub fn get_embedded_lua(name: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match name {\n");

    for (name, rel) in &entries {
        code.push_str(&format!(
            "        \"{name}\" => Some(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\"))),\n"
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    let libs_glob = libs_dir.to_str().unwrap_or("").replace('\\', "/");
    println!("cargo:rerun-if-changed={libs_glob}");
}
